from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views

#app_name = 'sotuken'

urlpatterns = [
    path('', views.book, name='book'),
    # path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/',views.profile,name = 'profile'),
    path('contact/',views.contact,name = 'contact'),
    path('contact/comp/',views.contact_comp,name = 'contact_comp'),
    path('lendhistory/',views.lendhistory,name = 'lendhistory'),
    path('camera', views.camera, name='camera'),
    path('camera/check', views.camera_check, name='camera_check'),
    path('lend/check', views.lend_check, name='lend_check'),
    path('lend/comp', views.lend_comp, name='lend_comp'),
    path('returns', views.returns, name='returns'),
    path('returns/check', views.returns_check, name='returns_check'),
    path('returns/comp',views.returns_comp, name='returns_comp'),
    path('search',views.search, name='search'),
    path('details/<int:num>',views.details,name='details'),
    path('manage',views.manage,name='manage'),
    path('manage/user',views.manage_user,name='manage_user'),
    path('manage/user/add',views.manage_user_add,name='manage_user_add'),
    path('manage/user/edit/<int:id>',views.manage_user_edit,name='manage_user_edit'),
    path('manage/user/edit/comp',views.manage_user_edit_comp,name='manage_user_edit_comp'),
    path('manage/user/delete',views.manage_user_delete,name='manage_user_delete'),
    path('manage/user/delete/comp',views.manage_user_delete_comp,name='manage_user_delete_comp'),
    path('manage/user/send/mail',views.manage_user_pass_re,name='manage_user_pass_re'),
    path('manage/user/send/mail/comp',views.manage_user_pass_send_comp,name='manage_user_pass_send_comp'),
    path('manage/booktable',views.manage_booktable,name='manage_booktable'),
    path('manage/bookdata',views.manage_bookdata,name='manage_bookdata'),
    path('manage/bookdata/add',views.manage_bookdata_add,name='manage_bookdata_add'),
    path('manage/bookdata/add/comp',views.manage_bookdata_add_comp,name='manage_bookdata_add_comp'),
    path('manage/bookdata/add/camera',views.manage_bookdata_add_camera,name='manage_bookdata_add_camera'),
    path('manage/bookdata/edit/<int:id>',views.manage_bookdata_edit,name='manage_bookdata_edit'),
    path('manage/bookdata/edit/comp',views.manage_bookdata_edit_comp,name='manage_bookdata_edit_comp'),
    path('manage/bookdata/delete/',views.manage_bookdata_delete,name='manage_bookdata_delete'),
    path('manage/bookdata/delete/comp',views.manage_bookdata_delete_comp,name='manage_bookdata_delete_comp'),
    path('manage/bigcat',views.manage_bigcat,name='manage_bigcat'),
    path('manage/bigcat/add',views.manage_bigcat_add,name='manage_bigcat_add'),
    path('manage/bigcat/add/comp',views.manage_bigcat_add_comp,name='manage_bigcat_add_comp'),
    path('manage/bigcat/edit/<int:id>',views.manage_bigcat_edit,name='manage_bigcat_edit'),
    path('manage/bigcat/edit/comp',views.manage_bigcat_edit_comp,name='manage_bigcat_edit_comp'),
    path('manage/bigcat/delete/<int:id>',views.manage_bigcat_delete,name='manage_bigcat_delete'),
    path('manage/bigcat/delete/comp',views.manage_bigcat_delete_comp,name='manage_bigcat_delete_comp'),
    path('manage/midcat',views.manage_midcat,name='manage_midcat'),
    path('manage/midcat/add',views.manage_midcat_add,name='manage_midcat_add'),
    path('manage/midcat/add/comp',views.manage_midcat_add_comp,name='manage_midcat_add_comp'),
    path('manage/midcat/edit/<int:id>',views.manage_midcat_edit,name='manage_midcat_edit'),
    path('manage/midcat/edit/comp',views.manage_midcat_edit_comp,name='manage_midcat_edit_comp'),
    path('manage/midcat/delete/<int:id>',views.manage_midcat_delete,name='manage_midcat_delete'),
    path('manage/midcat/delete/comp',views.manage_midcat_delete_comp,name='manage_midcat_delete_comp'),
    path('manage/lendtable',views.manage_lendtable,name='manage_lendtable'),
    path('manage/lend',views.manage_lend,name='manage_lend'),
    path('manage/lend/edit/<int:id>',views.manage_lend_edit,name='manage_lend_edit'),
    path('manage/lend/edit/comp',views.manage_lend_edit_comp,name='manage_lend_edit_comp'),
    path('manage/lendhistory',views.manage_lendhistory,name='manage_lendhistory'),
]
